#pragma once

// codes from sdfmFont.h
#define ICON_SDFM_TRASH_CAN_OUTLINE u8"\ufa79"
#define ICON_SDFM_PAUSE u8"\uf3e4"
#define ICON_SDFM_PLAY u8"\uf40a"
#define ICON_SDFM_PENCIL u8"\uf3eb"
#define ICON_SDFM_LOCK u8"\uf33e"

#define LUMO_BACKEND_ICON_LABEL_RESET ICON_SDFM_TRASH_CAN_OUTLINE
#define LUMO_BACKEND_ICON_LABEL_PAUSE ICON_SDFM_PAUSE
#define LUMO_BACKEND_ICON_LABEL_PLAY ICON_SDFM_PLAY
#define LUMO_BACKEND_ICON_LABEL_EDIT ICON_SDFM_PENCIL
#define LUMO_BACKEND_CAMERA_ICON_LABEL_LOCK ICON_SDFM_LOCK
