set(TINYEXPRCPP_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/tinyexpr-plusplus)
set(TINYEXPRCPP_LIBRARIES TinyExpr)

file(GLOB TINYEXPRCPP_SOURCES ${TINYEXPRCPP_INCLUDE_DIR}/tinyexpr.cpp)
file(GLOB TINYEXPRCPP_HEADERS ${TINYEXPRCPP_INCLUDE_DIR}/tinyexpr.h)
                 
add_library(${TINYEXPRCPP_LIBRARIES} STATIC ${TINYEXPRCPP_SOURCES} ${TINYEXPRCPP_HEADERS})
    
set_target_properties(${TINYEXPRCPP_LIBRARIES} PROPERTIES LINKER_LANGUAGE CXX)
set_target_properties(${TINYEXPRCPP_LIBRARIES} PROPERTIES FOLDER Lumo_Libs)

message(STATUS "TINYEXPRCPP_INCLUDE_DIR : ${TINYEXPRCPP_INCLUDE_DIR}")
message(STATUS "TINYEXPRCPP_LIBRARIES : ${TINYEXPRCPP_LIBRARIES}")
