/*
Copyright 2022-2022 Stephane Cuillerdier (aka aiekick)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//Header Generated with https://github.com/aiekick/ImGuiFontStudio
//Based on https://github.com/juliettef/IconFontCppHeaders
//for Language c++

#pragma once

#define FONT_ICON_BUFFER_NAME_NDP NDP_compressed_data_base85
#define FONT_ICON_BUFFER_SIZE_NDP 0x4425

#define ICON_MIN_NDP 0xf00a
#define ICON_MAX_NDP 0xfffa

#define ICON_NDP_ADD u8"\uffb7"
#define ICON_NDP_ANGLE_DOWN u8"\uff8e"
#define ICON_NDP_ANGLE_LEFT u8"\uff91"
#define ICON_NDP_ANGLE_RIGHT u8"\uff90"
#define ICON_NDP_ANGLE_UP u8"\uff8f"
#define ICON_NDP_ARROWS u8"\uffd9"
#define ICON_NDP_ARROWS_ALT u8"\uffa6"
#define ICON_NDP_ARROW_CIRCLE_DOWN u8"\uffa7"
#define ICON_NDP_ARROW_CIRCLE_LEFT u8"\uffaa"
#define ICON_NDP_ARROW_CIRCLE_O_LEFT u8"\uff60"
#define ICON_NDP_ARROW_CIRCLE_O_RIGHT u8"\uff61"
#define ICON_NDP_ARROW_CIRCLE_RIGHT u8"\uffa9"
#define ICON_NDP_ARROW_CIRCLE_UP u8"\uffa8"
#define ICON_NDP_ARROW_DOWN u8"\uffb9"
#define ICON_NDP_ARROW_LEFT u8"\uffbd"
#define ICON_NDP_ARROW_RIGHT u8"\uffbc"
#define ICON_NDP_ARROW_UP u8"\uffba"
#define ICON_NDP_BACKWARD u8"\uffd5"
#define ICON_NDP_BAN u8"\uffbf"
#define ICON_NDP_BOOKMARK u8"\uffe6"
#define ICON_NDP_CANCEL u8"\ufff5"
#define ICON_NDP_CARET_DOWN u8"\uffa0"
#define ICON_NDP_CARET_LEFT u8"\uff9d"
#define ICON_NDP_CARET_RIGHT u8"\uff9c"
#define ICON_NDP_CARET_SQUARE_O_DOWN u8"\uff77"
#define ICON_NDP_CARET_SQUARE_O_LEFT u8"\uff5f"
#define ICON_NDP_CARET_SQUARE_O_RIGHT u8"\uff72"
#define ICON_NDP_CARET_SQUARE_O_UP u8"\uff74"
#define ICON_NDP_CARET_UP u8"\uff9e"
#define ICON_NDP_CHECK_CIRCLE u8"\uffc6"
#define ICON_NDP_CHECK_CIRCLE_O u8"\uffc0"
#define ICON_NDP_CHECK_SQUARE u8"\uff7b"
#define ICON_NDP_CHECK_SQUARE_O u8"\uffdb"
#define ICON_NDP_CHEVRON_DOWN u8"\uffb0"
#define ICON_NDP_CHEVRON_UP u8"\uffb1"
#define ICON_NDP_CLOCK_O u8"\uffef"
#define ICON_NDP_CODE_FORK u8"\uff8a"
#define ICON_NDP_COG u8"\ufff2"
#define ICON_NDP_COGS u8"\uffad"
#define ICON_NDP_CROSSHAIRS u8"\uffc2"
#define ICON_NDP_DESTROY u8"\ufff1"
#define ICON_NDP_DOT_CIRCLE_O u8"\uff5e"
#define ICON_NDP_DRIVES u8"\uff3d"
#define ICON_NDP_EJECT u8"\uffcb"
#define ICON_NDP_EXCLAMATION_CIRCLE u8"\uffb5"
#define ICON_NDP_EXCLAMATION_TRIANGLE u8"\uffb2"
#define ICON_NDP_EXTERNAL_LINK_SQUARE u8"\uff79"
#define ICON_NDP_EYE u8"\uffb4"
#define ICON_NDP_EYE_SLASH u8"\uffb3"
#define ICON_NDP_FAST_BACKWARD u8"\uffd7"
#define ICON_NDP_FAST_FORWARD u8"\uffce"
#define ICON_NDP_FILE u8"\uf15b"
#define ICON_NDP_FILES_O u8"\uffa3"
#define ICON_NDP_FILE_ARCHIVE_O u8"\uff54"
#define ICON_NDP_FILE_AUDIO_O u8"\uff53"
#define ICON_NDP_FILE_CODE_O u8"\uff51"
#define ICON_NDP_FILE_GRID_THUMBNAILS u8"\uf00a"
#define ICON_NDP_FILE_IMAGE_O u8"\uff55"
#define ICON_NDP_FILE_LIST u8"\uf0c9"
#define ICON_NDP_FILE_LIST_THUMBNAILS u8"\uf00b"
#define ICON_NDP_FILE_O u8"\ufff0"
#define ICON_NDP_FILE_TEXT u8"\uff70"
#define ICON_NDP_FILE_TEXT_O u8"\uff95"
#define ICON_NDP_FILE_VIDEO_O u8"\uff52"
#define ICON_NDP_FOLDER_OPEN u8"\uffaf"
#define ICON_NDP_FORWARD u8"\uffd0"
#define ICON_NDP_GAMEPAD u8"\uff8c"
#define ICON_NDP_HEART_O u8"\uffac"
#define ICON_NDP_INFO u8"\uff88"
#define ICON_NDP_INFO_CIRCLE u8"\uffc3"
#define ICON_NDP_KEYBOARD_O u8"\uff8b"
#define ICON_NDP_LINK u8"\uffa5"
#define ICON_NDP_MAP_SIGNS u8"\uff34"
#define ICON_NDP_MICROPHONE u8"\uff84"
#define ICON_NDP_MICROPHONE_SLASH u8"\uff83"
#define ICON_NDP_MINUS_CIRCLE u8"\uffc8"
#define ICON_NDP_MINUS_SQUARE u8"\uff7c"
#define ICON_NDP_MUSIC u8"\ufffa"
#define ICON_NDP_OK u8"\ufff6"
#define ICON_NDP_PAPERCLIP u8"\uffa2"
#define ICON_NDP_PAUSE u8"\uffd2"
#define ICON_NDP_PENCIL_SQUARE u8"\uff7a"
#define ICON_NDP_PENCIL_SQUARE_O u8"\uffdd"
#define ICON_NDP_PICTURE_O u8"\uffe2"
#define ICON_NDP_PLAY u8"\uffd4"
#define ICON_NDP_PLUS_CIRCLE u8"\uffca"
#define ICON_NDP_PROJECT u8"\uf02d"
#define ICON_NDP_QUESTION u8"\uff89"
#define ICON_NDP_QUESTION_CIRCLE u8"\uffc4"
#define ICON_NDP_REFRESH u8"\uffeb"
#define ICON_NDP_REMOVE u8"\uffb6"
#define ICON_NDP_REPEAT u8"\uffec"
#define ICON_NDP_REPLY u8"\uff8d"
#define ICON_NDP_RESET u8"\uffb8"
#define ICON_NDP_SAVE u8"\uffa1"
#define ICON_NDP_SCISSORS u8"\uffa4"
#define ICON_NDP_SEARCH u8"\ufff9"
#define ICON_NDP_SEARCH_MINUS u8"\ufff3"
#define ICON_NDP_SEARCH_PLUS u8"\ufff4"
#define ICON_NDP_SHARE_SQUARE u8"\uff78"
#define ICON_NDP_SHARE_SQUARE_O u8"\uffdc"
#define ICON_NDP_SORT u8"\uff9b"
#define ICON_NDP_SORT_ASC u8"\uff99"
#define ICON_NDP_SORT_DESC u8"\uff9a"
#define ICON_NDP_STAR u8"\ufff8"
#define ICON_NDP_STAR_O u8"\ufff7"
#define ICON_NDP_STEP_BACKWARD u8"\uffd8"
#define ICON_NDP_STEP_FORWARD u8"\uffcd"
#define ICON_NDP_STOP u8"\uffd1"
#define ICON_NDP_TIMES_CIRCLE u8"\uffc7"
#define ICON_NDP_TIMES_CIRCLE_O u8"\uffc1"
#define ICON_NDP_UNDO u8"\uff97"
#define ICON_NDP_WINDOW_CLOSE u8"\uff2a"
#define ICON_NDP_WINDOW_CLOSE_O u8"\uff29"
#define ICON_NDP_WINDOW_MAXIMIZE u8"\uff2f"
#define ICON_NDP_WINDOW_MINIMIZE u8"\uff2d"
#define ICON_NDP_WINDOW_RESTORE u8"\uff2b"
