set(KISSFFT_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/kissfft)

set(KISSFFT_DATATYPE "float" CACHE STRING "")
set(KISSFFT_OPENMP ON CACHE BOOL "")
set(KISSFFT_PKGCONFIG OFF CACHE BOOL "")
set(KISSFFT_STATIC ON CACHE BOOL "")
set(KISSFFT_TEST OFF CACHE BOOL "")
set(KISSFFT_TOOLS OFF CACHE BOOL "")
set(KISSFFT_USE_ALLOCA OFF CACHE BOOL "")

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(LLVM_USE_CRT_DEBUG MTd CACHE STRING "" FORCE)
set(LLVM_USE_CRT_MINSIZEREL MT CACHE STRING "" FORCE)
set(LLVM_USE_CRT_RELEASE MT CACHE STRING "" FORCE)
set(LLVM_USE_CRT_RELWITHDEBINFO MT CACHE STRING "" FORCE)
set(USE_MSVC_RUNTIME_LIBRARY_DLL OFF CACHE BOOL "")

add_subdirectory(${KISSFFT_INCLUDE_DIR} EXCLUDE_FROM_ALL)
include_directories(${KISSFFT_INCLUDE_DIR})    

set_target_properties(kissfft PROPERTIES LINKER_LANGUAGE C)
set_target_properties(kissfft PROPERTIES FOLDER 3rdparty/Static)

set(KISSFFT_LIBRARIES kissfft)
