#pragma once

#define ICON_SDFM_TRASH_CAN_OUTLINE u8"\ufa79"
#define ICON_SDFM_PLUS u8"\uf415"
#define ICON_SDFM_MINUS u8"\uf374"

#define BUTTON_LABEL_RESET ICON_SDFM_TRASH_CAN_OUTLINE
#define BUTTON_LABEL_PLUS ICON_SDFM_PLUS
#define BUTTON_LABEL_MINUS ICON_SDFM_MINUS
