/*
MIT License

Copyright (c) 2022-2022 Stephane Cuillerdier (aka aiekick)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

//Header Generated with https://github.com/aiekick/ImGuiFontStudio
//Based on https://github.com/juliettef/IconFontCppHeaders
//for Language c++

#pragma once

#define FONT_ICON_BUFFER_NAME_CR CR_compressed_data_base85
#define FONT_ICON_BUFFER_SIZE_CR 0x9baf

#define ICON_MIN_CR 0x9
#define ICON_MAX_CR 0x2219

#define ICON_CR_A u8"\u61"
#define ICON_CR_AACUTE u8"\ue1"
#define ICON_CR_ACIRCUMFLEX u8"\ue2"
#define ICON_CR_ACUTE u8"\ub4"
#define ICON_CR_ADIERESIS u8"\ue4"
#define ICON_CR_AE u8"\ue6"
#define ICON_CR_AGRAVE u8"\ue0"
#define ICON_CR_AMPERSAND u8"\u26"
#define ICON_CR_ARING u8"\ue5"
#define ICON_CR_ASCIICIRCUM u8"\u5e"
#define ICON_CR_ASCIITILDE u8"\u7e"
#define ICON_CR_ASTERISK u8"\u2a"
#define ICON_CR_AT u8"\u40"
#define ICON_CR_ATILDE u8"\ue3"
#define ICON_CR_B u8"\u62"
#define ICON_CR_BACKSLASH u8"\u5c"
#define ICON_CR_BAR u8"\u7c"
#define ICON_CR_BRACELEFT u8"\u7b"
#define ICON_CR_BRACERIGHT u8"\u7d"
#define ICON_CR_BRACKETLEFT u8"\u5b"
#define ICON_CR_BRACKETRIGHT u8"\u5d"
#define ICON_CR_BROKENBAR u8"\ua6"
#define ICON_CR_BULLET u8"\u2022"
#define ICON_CR_C u8"\u63"
#define ICON_CR_CCEDILLA u8"\ue7"
#define ICON_CR_CEDILLA u8"\ub8"
#define ICON_CR_CENT u8"\ua2"
#define ICON_CR_CIRCUMFLEX u8"\u2c6"
#define ICON_CR_COLON u8"\u3a"
#define ICON_CR_COMMA u8"\u2c"
#define ICON_CR_COPYRIGHT u8"\ua9"
#define ICON_CR_CURRENCY u8"\ua4"
#define ICON_CR_D u8"\u64"
#define ICON_CR_DEGREE u8"\ub0"
#define ICON_CR_DIERESIS u8"\ua8"
#define ICON_CR_DIVIDE u8"\uf7"
#define ICON_CR_DOLLAR u8"\u24"
#define ICON_CR_DOTLESSI u8"\u131"
#define ICON_CR_DOT_NOTDEF u8"\u9"
#define ICON_CR_E u8"\u65"
#define ICON_CR_EACUTE u8"\ue9"
#define ICON_CR_ECIRCUMFLEX u8"\uea"
#define ICON_CR_EDIERESIS u8"\ueb"
#define ICON_CR_EGRAVE u8"\ue8"
#define ICON_CR_EIGHT u8"\u38"
#define ICON_CR_EMDASH u8"\u2014"
#define ICON_CR_ENDASH u8"\u2013"
#define ICON_CR_EQUAL u8"\u3d"
#define ICON_CR_ETH u8"\uf0"
#define ICON_CR_EURO u8"\u20ac"
#define ICON_CR_EXCLAM u8"\u21"
#define ICON_CR_EXCLAMDOWN u8"\ua1"
#define ICON_CR_F u8"\u66"
#define ICON_CR_FIVE u8"\u35"
#define ICON_CR_FOUR u8"\u34"
#define ICON_CR_FRACTION u8"\u2044"
#define ICON_CR_G u8"\u67"
#define ICON_CR_GERMANDBLS u8"\udf"
#define ICON_CR_GRAVE u8"\u60"
#define ICON_CR_GREATER u8"\u3e"
#define ICON_CR_GUILLEMOTLEFT u8"\uab"
#define ICON_CR_GUILLEMOTRIGHT u8"\ubb"
#define ICON_CR_GUILSINGLLEFT u8"\u2039"
#define ICON_CR_GUILSINGLRIGHT u8"\u203a"
#define ICON_CR_H u8"\u68"
#define ICON_CR_HYPHEN u8"\u2d"
#define ICON_CR_I u8"\u69"
#define ICON_CR_IACUTE u8"\ued"
#define ICON_CR_ICIRCUMFLEX u8"\uee"
#define ICON_CR_IDIERESIS u8"\uef"
#define ICON_CR_IGRAVE u8"\uec"
#define ICON_CR_J u8"\u6a"
#define ICON_CR_K u8"\u6b"
#define ICON_CR_L u8"\u6c"
#define ICON_CR_LESS u8"\u3c"
#define ICON_CR_LOGICALNOT u8"\uac"
#define ICON_CR_M u8"\u6d"
#define ICON_CR_MACRON u8"\uaf"
#define ICON_CR_MU u8"\ub5"
#define ICON_CR_MULTIPLY u8"\ud7"
#define ICON_CR_N u8"\u6e"
#define ICON_CR_NINE u8"\u39"
#define ICON_CR_NTILDE u8"\uf1"
#define ICON_CR_NUMBERSIGN u8"\u23"
#define ICON_CR_O u8"\u6f"
#define ICON_CR_OACUTE u8"\uf3"
#define ICON_CR_OCIRCUMFLEX u8"\uf4"
#define ICON_CR_ODIERESIS u8"\uf6"
#define ICON_CR_OE u8"\u153"
#define ICON_CR_OGRAVE u8"\uf2"
#define ICON_CR_ONE u8"\u31"
#define ICON_CR_ONEHALF u8"\ubd"
#define ICON_CR_ONEQUARTER u8"\ubc"
#define ICON_CR_ORDFEMININE u8"\uaa"
#define ICON_CR_ORDMASCULINE u8"\uba"
#define ICON_CR_OSLASH u8"\uf8"
#define ICON_CR_OTILDE u8"\uf5"
#define ICON_CR_P u8"\u70"
#define ICON_CR_PARAGRAPH u8"\ub6"
#define ICON_CR_PARENLEFT u8"\u28"
#define ICON_CR_PARENRIGHT u8"\u29"
#define ICON_CR_PERCENT u8"\u25"
#define ICON_CR_PERIOD u8"\u2e"
#define ICON_CR_PERIODCENTERED u8"\ub7"
#define ICON_CR_PLUS u8"\u2b"
#define ICON_CR_PLUSMINUS u8"\ub1"
#define ICON_CR_Q u8"\u71"
#define ICON_CR_QUESTION u8"\u3f"
#define ICON_CR_QUESTIONDOWN u8"\ubf"
#define ICON_CR_QUOTEDBL u8"\u22"
#define ICON_CR_QUOTEDBLBASE u8"\u201e"
#define ICON_CR_QUOTEDBLLEFT u8"\u201c"
#define ICON_CR_QUOTEDBLRIGHT u8"\u201d"
#define ICON_CR_QUOTELEFT u8"\u2018"
#define ICON_CR_QUOTERIGHT u8"\u2019"
#define ICON_CR_QUOTESINGLBASE u8"\u201a"
#define ICON_CR_QUOTESINGLE u8"\u27"
#define ICON_CR_R u8"\u72"
#define ICON_CR_REGISTERED u8"\uae"
#define ICON_CR_RING u8"\u2da"
#define ICON_CR_S u8"\u73"
#define ICON_CR_SECTION u8"\ua7"
#define ICON_CR_SEMICOLON u8"\u3b"
#define ICON_CR_SEVEN u8"\u37"
#define ICON_CR_SIX u8"\u36"
#define ICON_CR_SLASH u8"\u2f"
#define ICON_CR_SPACE u8"\u20"
#define ICON_CR_STERLING u8"\ua3"
#define ICON_CR_T u8"\u74"
#define ICON_CR_THORN u8"\ufe"
#define ICON_CR_THREE u8"\u33"
#define ICON_CR_THREEQUARTERS u8"\ube"
#define ICON_CR_TILDE u8"\u2dc"
#define ICON_CR_TWO u8"\u32"
#define ICON_CR_U u8"\u75"
#define ICON_CR_UACUTE u8"\ufa"
#define ICON_CR_UCIRCUMFLEX u8"\ufb"
#define ICON_CR_UDIERESIS u8"\ufc"
#define ICON_CR_UGRAVE u8"\uf9"
#define ICON_CR_UNDERSCORE u8"\u5f"
#define ICON_CR_UNI00B2 u8"\ub2"
#define ICON_CR_UNI00B3 u8"\ub3"
#define ICON_CR_UNI00B9 u8"\ub9"
#define ICON_CR_UNI2219 u8"\u2219"
#define ICON_CR_V u8"\u76"
#define ICON_CR_W u8"\u77"
#define ICON_CR_X u8"\u78"
#define ICON_CR_Y u8"\u79"
#define ICON_CR_YACUTE u8"\ufd"
#define ICON_CR_YDIERESIS u8"\uff"
#define ICON_CR_YEN u8"\ua5"
#define ICON_CR_Z u8"\u7a"
#define ICON_CR_ZERO u8"\u30"
