set(COMMON_INCLUDE_DIR)
set(COMMON_LIBRARIES)
set(COMMON_LIB_DIR)

add_subdirectory(${CMAKE_SOURCE_DIR}/MainLibs/Common)
set_target_properties(${COMMON_LIBRARIES} PROPERTIES FOLDER libs)
##set_target_properties(${COMMON_LIBRARIES} PROPERTIES LINK_FLAGS "/ignore:4244")

message(STATUS "COMMON_INCLUDE_DIR : ${COMMON_INCLUDE_DIR}")
message(STATUS "COMMON_LIBRARIES : ${COMMON_LIBRARIES}")
message(STATUS "COMMON_LIB_DIR : ${COMMON_LIB_DIR}")

set_target_properties(${COMMON_LIBRARIES} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${FINAL_BIN_DIR}")

