set(INTERFACEBLOCK_INCLUDE_DIR)
set(INTERFACEBLOCK_LIBRARIES)
set(INTERFACEBLOCK_LIB_DIR)

add_subdirectory(${CMAKE_SOURCE_DIR}/libs/InterfaceBlock)
set_target_properties(${INTERFACEBLOCK_LIBRARIES} PROPERTIES FOLDER Lumo_Libs/Static)
##set_target_properties(${INTERFACEBLOCK_LIBRARIES} PROPERTIES LINK_FLAGS "/ignore:4244")

message(STATUS "INTERFACEBLOCK_INCLUDE_DIR : ${INTERFACEBLOCK_INCLUDE_DIR}")
message(STATUS "INTERFACEBLOCK_LIBRARIES : ${INTERFACEBLOCK_LIBRARIES}")
message(STATUS "INTERFACEBLOCK_LIB_DIR : ${INTERFACEBLOCK_LIB_DIR}")


