set(UNIFORMWIDGETS_INCLUDE_DIR)
set(UNIFORMWIDGETS_LIBRARIES)
set(UNIFORMWIDGETS_LIB_DIR)

add_subdirectory(${CMAKE_SOURCE_DIR}/MainLibs/UniformWidgets)
set_target_properties(${UNIFORMWIDGETS_LIBRARIES} PROPERTIES FOLDER libs)
##set_target_properties(${UNIFORMWIDGETS_LIBRARIES} PROPERTIES LINK_FLAGS "/ignore:4244")

message(STATUS "UNIFORMWIDGETS_INCLUDE_DIR : ${UNIFORMWIDGETS_INCLUDE_DIR}")
message(STATUS "UNIFORMWIDGETS_LIBRARIES : ${UNIFORMWIDGETS_LIBRARIES}")
message(STATUS "UNIFORMWIDGETS_LIB_DIR : ${UNIFORMWIDGETS_LIB_DIR}")

