set(VKFRAMEWORK_INCLUDE_DIR)
set(VKFRAMEWORK_LIBRARIES)
set(VKFRAMEWORK_LIB_DIR)

add_subdirectory(${CMAKE_SOURCE_DIR}/libs/vkFramework)
set_target_properties(${VKFRAMEWORK_LIBRARIES} PROPERTIES FOLDER Lumo_Libs)
##set_target_properties(${VKFRAMEWORK_LIBRARIES} PROPERTIES LINK_FLAGS "/ignore:4244")

message(STATUS "VKFRAMEWORK_INCLUDE_DIR : ${VKFRAMEWORK_INCLUDE_DIR}")
message(STATUS "VKFRAMEWORK_LIBRARIES : ${VKFRAMEWORK_LIBRARIES}")
message(STATUS "VKFRAMEWORK_LIB_DIR : ${VKFRAMEWORK_LIB_DIR}")


